package com.yoni.financetracker.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import lombok.Data;

/**
 * This entity represents a budget allocation for a specific category. Budgets help users plan and
 * track their spending limits for different categories.
 *
 * <p>The @Entity annotation marks this class as a JPA entity, meaning it will be mapped to a
 * database table. The @Data annotation from Lombok automatically generates getters, setters,
 * toString, equals, and hashCode methods.
 */
@Entity
@Data
public class Budget {
  /**
   * Unique identifier for the budget entry. @GeneratedValue indicates that the ID will be
   * automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The category this budget is allocated for. @Enumerated(EnumType.STRING) stores the enum as a
   * string in the database.
   */
  @Enumerated(EnumType.STRING)
  private Category category;

  /**
   * The budget amount allocated for this category. Using BigDecimal for precise decimal
   * calculations with money.
   */
  private BigDecimal amount;

  /** The date when this budget was created or is effective from. */
  private LocalDate date;

  /**
   * Version field for optimistic locking. Helps prevent concurrent modification issues by tracking
   * changes to the entity.
   */
  @Version private Long version;
}
