package com.yoni.financetracker.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import lombok.Data;

/**
 * This entity represents an expenditure (expense) transaction in the finance tracker. Expenditure
 * records track money going out from the user's accounts for various purposes.
 *
 * <p>The @Entity annotation marks this class as a JPA entity, meaning it will be mapped to a
 * database table. @Data annotation from Lombok automatically generates getters, setters, toString,
 * equals, and hashCode methods.
 */
@Data
@Entity
@Table(name = "expenditure")
public class Expenditure {

  /**
   * Unique identifier for the expenditure entry. @GeneratedValue indicates that the ID will be
   * automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The amount spent in this expenditure. Using BigDecimal for precise decimal calculations with
   * money.
   */
  private BigDecimal amount;

  /**
   * A description of what the money was spent on. Helps users identify and track their spending.
   */
  private String description;

  /** The date when the expenditure occurred. Used for tracking and reporting purposes. */
  private LocalDate date;

  /**
   * The category this expenditure belongs to. Helps in organising and analysing spending
   * patterns. @Enumerated(EnumType.STRING) stores the enum as a string in the database.
   */
  @Enumerated(EnumType.STRING)
  private Category category;
}
