package com.yoni.financetracker.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDate;
import lombok.Data;

/**
 * This entity represents an income transaction in the finance tracker. Income records track money
 * coming into the user's accounts from various sources.
 *
 * <p>The @Entity annotation marks this class as a JPA entity, meaning it will be mapped to a
 * database table. @Data annotation from Lombok automatically generates getters, setters, toString,
 * equals, and hashCode methods.
 */
@Data
@Entity
@Table(name = "income")
public class Income {

  /**
   * Unique identifier for the income entry. @GeneratedValue indicates that the ID will be
   * automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The amount of income received. Using BigDecimal for precise decimal calculations with money.
   */
  private BigDecimal amount;

  /**
   * A description of the income source or purpose. Helps users identify and categorise their income
   * sources.
   */
  private String description;

  /** The date when the income was received. Used for tracking and reporting purposes. */
  private LocalDate date;
}
